 # schema.yml

 version: 2

 sources:
   - name: raw
     schema: gz_raw_data
     tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have on row per product_id found in each orders_id
        columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: foreign key to ship
           - name: pdt_id
             description: foreign key to product
           - name: revenue
             description: the amount paid by the customer to purchase the product. revenue = quantity * selling_price
           - name: quantity
             description: number of items purchase in one order
        tests:
           - unique:
               column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_newproduct
        description : product of Greenweez
        columns:
           - name: products_id
             description: Primary key
           - name: purchase_price
             description: purchase price of product

      - name: ship
        identifier: raw_gz_ship
        description: shipping data for Greenweez orders
        columns:
         - name: orders_id
           description: Primary key
         - name: shipping_fee
           description: price paid by customer for shipping
         - name: log_cost
           description: cost of preparing parcels in warehouse,etc
         - name: ship_cost
           description: shipping cost paid by Greenweez to logistics/ carrier company
          



